/**
 * HTML Exporter for Kindle clippings.
 *
 * Generates a standalone HTML file with:
 * - Embedded CSS (no external dependencies)
 * - Responsive design
 * - Dark mode support
 * - Search/filter functionality via vanilla JS
 * - Print-friendly styles
 *
 * @packageDocumentation
 */

import type { Clipping } from "#app-types/clipping.js";
import { groupByBook } from "#domain/analytics/stats.js";
import type { ExporterOptionsParsed } from "#schemas/exporter.schema.js";
import { formatDateHuman } from "#utils/system/dates.js";
import type { ExportedFile, ExportResult } from "../core/types.js";
import { BaseExporter } from "../shared/base-exporter.js";
import { getHtmlStyles } from "./html.styles.js";

/**
 * Extended options for HTML export.
 */
export interface HtmlExporterOptions extends ExporterOptionsParsed {
  /** Page title (default: "Kindle Highlights") */
  title?: string;
  /** Include search functionality (default: true) */
  includeSearch?: boolean;
  /** Include dark mode toggle (default: true) */
  includeDarkMode?: boolean;
  /** Custom CSS to inject */
  customCss?: string;
}

/**
 * Export clippings to standalone HTML format.
 */
export class HtmlExporter extends BaseExporter {
  readonly name = "html";
  readonly extension = ".html";

  /**
   * Export clippings to HTML.
   *
   * @param clippings - Clippings to export
   * @param options - Export options
   * @returns Export result with HTML content
   */
  protected async doExport(
    clippings: Clipping[],
    options: HtmlExporterOptions,
  ): Promise<ExportResult> {
    const title = options.title ?? this.DEFAULT_EXPORT_TITLE;
    const includeSearch = options.includeSearch ?? true;
    const includeDarkMode = options.includeDarkMode ?? true;

    const grouped = groupByBook(clippings);
    const html = this.generateHtml(
      grouped,
      title,
      includeSearch,
      includeDarkMode,
      options?.customCss,
    );

    if (options.groupByBook) {
      // Generate separate files per book
      const files: ExportedFile[] = [];

      for (const [bookTitle, bookClippings] of grouped) {
        const bookGrouped = new Map<string, Clipping[]>();
        bookGrouped.set(bookTitle, bookClippings);

        const first = bookClippings[0];
        const pageTitle = first?.title ?? bookTitle;
        const content = this.generateHtml(
          bookGrouped,
          pageTitle,
          includeSearch,
          includeDarkMode,
          options.customCss,
        );

        const safeTitle = this.sanitizeFilename(bookTitle);

        files.push({
          path: `${safeTitle}.html`,
          content,
        });
      }

      return this.success(html, files);
    }

    return this.success(html);
  }

  /**
   * Generate the complete HTML document.
   */
  private generateHtml(
    grouped: Map<string, Clipping[]>,
    title: string,
    includeSearch: boolean,
    includeDarkMode: boolean,
    customCss?: string,
  ): string {
    const totalClippings = Array.from(grouped.values()).reduce((sum, arr) => sum + arr.length, 0);
    const totalBooks = grouped.size;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(title)}</title>
  <style>
${getHtmlStyles(customCss)}
  </style>
</head>
<body>
  <header class="header">
    <h1>${this.escapeHtml(title)}</h1>
    <p class="stats">${totalBooks} book${totalBooks !== 1 ? "s" : ""} • ${totalClippings} highlight${totalClippings !== 1 ? "s" : ""}</p>
    ${includeDarkMode ? '<button id="theme-toggle" class="theme-toggle" aria-label="Toggle dark mode">&#x1F319;</button>' : ""}
  </header>

  ${includeSearch ? this.generateSearchBox() : ""}

  <main class="container">
    ${this.generateBooksHtml(grouped)}
  </main>

  <footer class="footer">
    <p>Generated by <a href="https://github.com/kindle-tools-ts" target="_blank">kindle-tools-ts</a> on ${new Date().toLocaleDateString()}</p>
  </footer>

  ${includeSearch || includeDarkMode ? this.getScript(includeSearch, includeDarkMode) : ""}
</body>
</html>`;
  }

  /**
   * Generate the search box HTML.
   */
  private generateSearchBox(): string {
    return `
  <div class="search-container">
    <input type="text" id="search" class="search-input" placeholder="Search highlights..." aria-label="Search highlights">
    <span class="search-count" id="search-count"></span>
  </div>`;
  }

  /**
   * Generate HTML for all books.
   */
  private generateBooksHtml(grouped: Map<string, Clipping[]>): string {
    const books: string[] = [];

    for (const [bookTitle, clippings] of grouped) {
      const first = clippings[0];
      if (!first) continue;

      books.push(`
    <article class="book" data-title="${this.escapeHtml(bookTitle.toLowerCase())}">
      <header class="book-header">
        <h2 class="book-title">${this.escapeHtml(first.title)}</h2>
        <p class="book-author">by ${this.escapeHtml(first.author)}</p>
        <span class="book-count">${clippings.length} highlight${clippings.length !== 1 ? "s" : ""}</span>
      </header>
      <div class="clippings">
        ${clippings.map((c) => this.generateClippingHtml(c)).join("\n        ")}
      </div>
    </article>`);
    }

    return books.join("\n");
  }

  /**
   * Generate HTML for a single clipping.
   */
  private generateClippingHtml(clipping: Clipping): string {
    const typeClass = `clipping-${clipping.type}`;
    const typeEmoji =
      clipping.type === "highlight"
        ? "\\u{1F4D6}"
        : clipping.type === "note"
          ? "\\u{1F4DD}"
          : "\\u{1F516}";
    const locationInfo = `Page ${clipping.page ?? "?"} • Location ${clipping.location.raw}`;
    const dateStr = clipping.date ? formatDateHuman(clipping.date) : "";

    let contentHtml = "";
    if (clipping.type === "highlight") {
      contentHtml = `<blockquote class="clipping-content">${this.escapeHtml(clipping.content)}</blockquote>`;
      if (clipping.note) {
        contentHtml += `<div class="clipping-note"><strong>Note:</strong> ${this.escapeHtml(clipping.note)}</div>`;
      }
    } else if (clipping.type === "note") {
      contentHtml = `<p class="clipping-content note-content">${this.escapeHtml(clipping.content)}</p>`;
    } else {
      contentHtml = `<p class="clipping-content bookmark-content"><em>Bookmark</em></p>`;
    }

    return `
        <div class="clipping ${typeClass}" data-content="${this.escapeHtml(clipping.content.toLowerCase())}">
          <div class="clipping-meta">
            <span class="clipping-type">${typeEmoji}</span>
            <span class="clipping-location">${locationInfo}</span>
            ${dateStr ? `<span class="clipping-date">${dateStr}</span>` : ""}
          </div>
          ${contentHtml}
        </div>`;
  }

  /**
   * Get embedded JavaScript for interactivity.
   */
  private getScript(includeSearch: boolean, includeDarkMode: boolean): string {
    const searchScript = includeSearch
      ? `
    const searchInput = document.getElementById('search');
    const searchCount = document.getElementById('search-count');
    const clippings = document.querySelectorAll('.clipping');
    const books = document.querySelectorAll('.book');

    searchInput.addEventListener('input', function(e) {
      const query = e.target.value.toLowerCase().trim();
      let visibleCount = 0;

      clippings.forEach(clipping => {
        const content = clipping.getAttribute('data-content') || '';
        const matches = query === '' || content.includes(query);
        clipping.classList.toggle('hidden', !matches);
        if (matches) visibleCount++;
      });

      // Hide books with no visible clippings
      books.forEach(book => {
        const visibleClippings = book.querySelectorAll('.clipping:not(.hidden)');
        book.classList.toggle('hidden', visibleClippings.length === 0);
      });

      searchCount.textContent = query ? visibleCount + ' result' + (visibleCount !== 1 ? 's' : '') : '';
    });`
      : "";

    const darkModeScript = includeDarkMode
      ? `
    const themeToggle = document.getElementById('theme-toggle');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

    // Check for saved preference or use system preference
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'dark' || (!savedTheme && prefersDark)) {
      document.body.classList.add('dark');
      themeToggle.textContent = '\\u2600'; // Sun emoji
    }

    themeToggle.addEventListener('click', function() {
      document.body.classList.toggle('dark');
      const isDark = document.body.classList.contains('dark');
      themeToggle.textContent = isDark ? '\\u2600' : '\\u{1F319}'; // Sun or Crescent Moon emoji
      localStorage.setItem('theme', isDark ? 'dark' : 'light');
    });`
      : "";

    return `
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      ${searchScript}
      ${darkModeScript}
    });
  </script>`;
  }
}
