/**
 * HTML Exporter for Kindle clippings.
 *
 * Generates a standalone HTML file with:
 * - Embedded CSS (no external dependencies)
 * - Responsive design
 * - Dark mode support
 * - Search/filter functionality via vanilla JS
 * - Print-friendly styles
 *
 * @packageDocumentation
 */

import type { Clipping } from "../types/clipping.js";
import type { ExportedFile, Exporter, ExporterOptions, ExportResult } from "../types/exporter.js";
import { groupByBook } from "../utils/stats.js";

/**
 * Extended options for HTML export.
 */
export interface HtmlExporterOptions extends ExporterOptions {
  /** Page title (default: "Kindle Highlights") */
  title?: string;
  /** Include search functionality (default: true) */
  includeSearch?: boolean;
  /** Include dark mode toggle (default: true) */
  includeDarkMode?: boolean;
  /** Custom CSS to inject */
  customCss?: string;
}

/**
 * Export clippings to standalone HTML format.
 */
export class HtmlExporter implements Exporter {
  name = "html";
  extension = ".html";

  /**
   * Export clippings to HTML.
   *
   * @param clippings - Clippings to export
   * @param options - Export options
   * @returns Export result with HTML content
   */
  async export(clippings: Clipping[], options?: HtmlExporterOptions): Promise<ExportResult> {
    try {
      const title = options?.title ?? "Kindle Highlights";
      const includeSearch = options?.includeSearch ?? true;
      const includeDarkMode = options?.includeDarkMode ?? true;

      const grouped = groupByBook(clippings);
      const html = this.generateHtml(
        grouped,
        title,
        includeSearch,
        includeDarkMode,
        options?.customCss,
      );

      if (options?.groupByBook) {
        // Generate separate files per book
        const files: ExportedFile[] = [];

        for (const [bookTitle, bookClippings] of grouped) {
          const bookGrouped = new Map<string, Clipping[]>();
          bookGrouped.set(bookTitle, bookClippings);

          const first = bookClippings[0];
          const pageTitle = first?.title ?? bookTitle;
          const content = this.generateHtml(
            bookGrouped,
            pageTitle,
            includeSearch,
            includeDarkMode,
            options?.customCss,
          );

          const safeTitle = bookTitle.replace(/[<>:"/\\|?*]/g, "-").slice(0, 100);

          files.push({
            path: `${safeTitle}.html`,
            content,
          });
        }

        return {
          success: true,
          output: html,
          files,
        };
      }

      return {
        success: true,
        output: html,
      };
    } catch (error) {
      return {
        success: false,
        output: "",
        error: error instanceof Error ? error : new Error(String(error)),
      };
    }
  }

  /**
   * Generate the complete HTML document.
   */
  private generateHtml(
    grouped: Map<string, Clipping[]>,
    title: string,
    includeSearch: boolean,
    includeDarkMode: boolean,
    customCss?: string,
  ): string {
    const totalClippings = Array.from(grouped.values()).reduce((sum, arr) => sum + arr.length, 0);
    const totalBooks = grouped.size;

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(title)}</title>
  <style>
${this.getStyles(customCss)}
  </style>
</head>
<body>
  <header class="header">
    <h1>${this.escapeHtml(title)}</h1>
    <p class="stats">${totalBooks} book${totalBooks !== 1 ? "s" : ""} • ${totalClippings} highlight${totalClippings !== 1 ? "s" : ""}</p>
    ${includeDarkMode ? '<button id="theme-toggle" class="theme-toggle" aria-label="Toggle dark mode">🌙</button>' : ""}
  </header>

  ${includeSearch ? this.generateSearchBox() : ""}

  <main class="container">
    ${this.generateBooksHtml(grouped)}
  </main>

  <footer class="footer">
    <p>Generated by <a href="https://github.com/kindle-tools-ts" target="_blank">kindle-tools-ts</a> on ${new Date().toLocaleDateString()}</p>
  </footer>

  ${includeSearch || includeDarkMode ? this.getScript(includeSearch, includeDarkMode) : ""}
</body>
</html>`;
  }

  /**
   * Generate the search box HTML.
   */
  private generateSearchBox(): string {
    return `
  <div class="search-container">
    <input type="text" id="search" class="search-input" placeholder="Search highlights..." aria-label="Search highlights">
    <span class="search-count" id="search-count"></span>
  </div>`;
  }

  /**
   * Generate HTML for all books.
   */
  private generateBooksHtml(grouped: Map<string, Clipping[]>): string {
    const books: string[] = [];

    for (const [bookTitle, clippings] of grouped) {
      const first = clippings[0];
      if (!first) continue;

      books.push(`
    <article class="book" data-title="${this.escapeHtml(bookTitle.toLowerCase())}">
      <header class="book-header">
        <h2 class="book-title">${this.escapeHtml(first.title)}</h2>
        <p class="book-author">by ${this.escapeHtml(first.author)}</p>
        <span class="book-count">${clippings.length} highlight${clippings.length !== 1 ? "s" : ""}</span>
      </header>
      <div class="clippings">
        ${clippings.map((c) => this.generateClippingHtml(c)).join("\n        ")}
      </div>
    </article>`);
    }

    return books.join("\n");
  }

  /**
   * Generate HTML for a single clipping.
   */
  private generateClippingHtml(clipping: Clipping): string {
    const typeClass = `clipping-${clipping.type}`;
    const typeEmoji = clipping.type === "highlight" ? "📖" : clipping.type === "note" ? "📝" : "🔖";
    const locationInfo = `Page ${clipping.page ?? "?"} • Location ${clipping.location.raw}`;
    const dateStr = clipping.date ? clipping.date.toLocaleDateString() : "";

    let contentHtml = "";
    if (clipping.type === "highlight") {
      contentHtml = `<blockquote class="clipping-content">${this.escapeHtml(clipping.content)}</blockquote>`;
      if (clipping.note) {
        contentHtml += `<div class="clipping-note"><strong>Note:</strong> ${this.escapeHtml(clipping.note)}</div>`;
      }
    } else if (clipping.type === "note") {
      contentHtml = `<p class="clipping-content note-content">${this.escapeHtml(clipping.content)}</p>`;
    } else {
      contentHtml = `<p class="clipping-content bookmark-content"><em>Bookmark</em></p>`;
    }

    return `
        <div class="clipping ${typeClass}" data-content="${this.escapeHtml(clipping.content.toLowerCase())}">
          <div class="clipping-meta">
            <span class="clipping-type">${typeEmoji}</span>
            <span class="clipping-location">${locationInfo}</span>
            ${dateStr ? `<span class="clipping-date">${dateStr}</span>` : ""}
          </div>
          ${contentHtml}
        </div>`;
  }

  /**
   * Get embedded CSS styles.
   */
  private getStyles(customCss?: string): string {
    return `
    :root {
      --bg-primary: #ffffff;
      --bg-secondary: #f8f9fa;
      --bg-tertiary: #e9ecef;
      --text-primary: #212529;
      --text-secondary: #6c757d;
      --accent: #4361ee;
      --border: #dee2e6;
      --shadow: rgba(0, 0, 0, 0.1);
      --quote-bg: #f8f9fa;
      --quote-border: #4361ee;
    }

    .dark {
      --bg-primary: #1a1a2e;
      --bg-secondary: #16213e;
      --bg-tertiary: #0f3460;
      --text-primary: #eaeaea;
      --text-secondary: #a0a0a0;
      --accent: #4cc9f0;
      --border: #2a2a4a;
      --shadow: rgba(0, 0, 0, 0.3);
      --quote-bg: #16213e;
      --quote-border: #4cc9f0;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: var(--bg-primary);
      color: var(--text-primary);
      line-height: 1.6;
      min-height: 100vh;
    }

    .header {
      background: var(--bg-secondary);
      padding: 2rem;
      text-align: center;
      border-bottom: 1px solid var(--border);
      position: relative;
    }

    .header h1 {
      font-size: 2rem;
      font-weight: 700;
      margin-bottom: 0.5rem;
    }

    .stats {
      color: var(--text-secondary);
      font-size: 0.9rem;
    }

    .theme-toggle {
      position: absolute;
      top: 1rem;
      right: 1rem;
      background: var(--bg-tertiary);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 0.5rem 1rem;
      cursor: pointer;
      font-size: 1.2rem;
      transition: all 0.2s;
    }

    .theme-toggle:hover {
      background: var(--accent);
      color: white;
    }

    .search-container {
      max-width: 800px;
      margin: 1.5rem auto;
      padding: 0 1rem;
      position: relative;
    }

    .search-input {
      width: 100%;
      padding: 1rem 1.5rem;
      font-size: 1rem;
      border: 2px solid var(--border);
      border-radius: 12px;
      background: var(--bg-primary);
      color: var(--text-primary);
      transition: all 0.2s;
    }

    .search-input:focus {
      outline: none;
      border-color: var(--accent);
      box-shadow: 0 0 0 3px rgba(67, 97, 238, 0.2);
    }

    .search-count {
      position: absolute;
      right: 1.5rem;
      top: 50%;
      transform: translateY(-50%);
      color: var(--text-secondary);
      font-size: 0.9rem;
    }

    .container {
      max-width: 900px;
      margin: 0 auto;
      padding: 1rem;
    }

    .book {
      background: var(--bg-secondary);
      border-radius: 16px;
      margin-bottom: 2rem;
      overflow: hidden;
      box-shadow: 0 4px 6px var(--shadow);
    }

    .book-header {
      background: var(--bg-tertiary);
      padding: 1.5rem;
      border-bottom: 1px solid var(--border);
    }

    .book-title {
      font-size: 1.4rem;
      font-weight: 600;
      margin-bottom: 0.25rem;
    }

    .book-author {
      color: var(--text-secondary);
      font-style: italic;
      margin-bottom: 0.5rem;
    }

    .book-count {
      display: inline-block;
      background: var(--accent);
      color: white;
      padding: 0.25rem 0.75rem;
      border-radius: 999px;
      font-size: 0.8rem;
      font-weight: 500;
    }

    .clippings {
      padding: 1rem;
    }

    .clipping {
      padding: 1rem;
      margin-bottom: 1rem;
      border-radius: 8px;
      background: var(--bg-primary);
      border-left: 4px solid var(--quote-border);
    }

    .clipping:last-child {
      margin-bottom: 0;
    }

    .clipping-meta {
      display: flex;
      gap: 1rem;
      font-size: 0.85rem;
      color: var(--text-secondary);
      margin-bottom: 0.75rem;
      flex-wrap: wrap;
    }

    .clipping-type {
      font-size: 1.1rem;
    }

    .clipping-content {
      font-size: 1rem;
      line-height: 1.7;
    }

    blockquote.clipping-content {
      border-left: none;
      padding: 0;
      margin: 0;
      font-style: italic;
    }

    .clipping-note {
      margin-top: 1rem;
      padding: 0.75rem;
      background: var(--bg-tertiary);
      border-radius: 6px;
      font-size: 0.9rem;
    }

    .clipping-highlight {
      border-left-color: #4361ee;
    }

    .clipping-note-type {
      border-left-color: #f72585;
    }

    .clipping-bookmark {
      border-left-color: #4cc9f0;
    }

    .footer {
      text-align: center;
      padding: 2rem;
      color: var(--text-secondary);
      font-size: 0.85rem;
      border-top: 1px solid var(--border);
    }

    .footer a {
      color: var(--accent);
      text-decoration: none;
    }

    .footer a:hover {
      text-decoration: underline;
    }

    .hidden {
      display: none !important;
    }

    @media print {
      .theme-toggle,
      .search-container {
        display: none;
      }

      .book {
        break-inside: avoid;
        box-shadow: none;
        border: 1px solid #ddd;
      }
    }

    @media (max-width: 600px) {
      .header h1 {
        font-size: 1.5rem;
      }

      .book-title {
        font-size: 1.2rem;
      }

      .clipping-meta {
        flex-direction: column;
        gap: 0.25rem;
      }
    }

    ${customCss ?? ""}`;
  }

  /**
   * Get embedded JavaScript for interactivity.
   */
  private getScript(includeSearch: boolean, includeDarkMode: boolean): string {
    const searchScript = includeSearch
      ? `
    const searchInput = document.getElementById('search');
    const searchCount = document.getElementById('search-count');
    const clippings = document.querySelectorAll('.clipping');
    const books = document.querySelectorAll('.book');

    searchInput.addEventListener('input', function(e) {
      const query = e.target.value.toLowerCase().trim();
      let visibleCount = 0;

      clippings.forEach(clipping => {
        const content = clipping.getAttribute('data-content') || '';
        const matches = query === '' || content.includes(query);
        clipping.classList.toggle('hidden', !matches);
        if (matches) visibleCount++;
      });

      // Hide books with no visible clippings
      books.forEach(book => {
        const visibleClippings = book.querySelectorAll('.clipping:not(.hidden)');
        book.classList.toggle('hidden', visibleClippings.length === 0);
      });

      searchCount.textContent = query ? visibleCount + ' result' + (visibleCount !== 1 ? 's' : '') : '';
    });`
      : "";

    const darkModeScript = includeDarkMode
      ? `
    const themeToggle = document.getElementById('theme-toggle');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

    // Check for saved preference or use system preference
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'dark' || (!savedTheme && prefersDark)) {
      document.body.classList.add('dark');
      themeToggle.textContent = '☀️';
    }

    themeToggle.addEventListener('click', function() {
      document.body.classList.toggle('dark');
      const isDark = document.body.classList.contains('dark');
      themeToggle.textContent = isDark ? '☀️' : '🌙';
      localStorage.setItem('theme', isDark ? 'dark' : 'light');
    });`
      : "";

    return `
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      ${searchScript}
      ${darkModeScript}
    });
  </script>`;
  }

  /**
   * Escape HTML special characters.
   */
  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }
}
